import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css"; 
import Navigation from "./components/nav";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SkinLens",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div >
      {/* <main> */}
    {/* <Navigation/> */}
      {/* <body className={inter.className}>{children}
      </body> */}
      {children}
      {/* </main> */}
    </div>
  );
}
